//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputAction_1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputAction_1 : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputAction_1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAction_1"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3306ed2d-216e-46d2-b13c-8ac1f5870270"",
            ""actions"": [
                {
                    ""name"": ""Attack_01"",
                    ""type"": ""Button"",
                    ""id"": ""ee799b9b-7fc2-4b9a-a60f-bb750a9643c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""25e4566c-a732-417b-bf4c-21610876e192"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeUP"",
                    ""type"": ""Button"",
                    ""id"": ""b8185b59-b069-4015-82f4-c169358ec341"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeDown"",
                    ""type"": ""Button"",
                    ""id"": ""47e7f5ac-5fab-4747-902c-8bee0b9be59c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack_02"",
                    ""type"": ""Button"",
                    ""id"": ""204be788-4676-41f2-96c1-7c0a8d969b27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""112be7a1-2ce9-4ed2-9056-231fd953d834"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f6937de2-5cf1-41ad-a97e-77804f459e42"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2210111d-410d-4633-92c0-c581018a928e"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""31f343a8-138e-4fd9-8e5b-2a389858e74e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""263e997b-8136-4b77-950c-8fb4a291b9a8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2abe7363-832a-4488-9b83-3d3ade088a0a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""177ad758-cc7a-402a-80f2-f18795a82784"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c8d73d57-9087-430c-8f38-b2fd32af8a7e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""10cec33a-5992-4e78-ab96-91b1f688ed41"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f50f2be7-2380-4a41-b077-2f4d3ffbf78f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9bda2d3-b787-4c56-a6ff-217e9f9e01af"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e4ba33b-643c-465e-8c13-59141ab32bf0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6253947-fcf6-4214-a235-dc024d193044"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51c2fb62-b48c-49fa-adad-024b6da059dd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df54d254-802f-402b-a485-8303efb9423c"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack_02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aef15f3e-44c6-49fc-97cb-3dd939c773b1"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc50b27e-eb28-4416-9e0e-dd37b96e9951"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Attack_01 = m_Player.FindAction("Attack_01", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_ChangeUP = m_Player.FindAction("ChangeUP", throwIfNotFound: true);
        m_Player_ChangeDown = m_Player.FindAction("ChangeDown", throwIfNotFound: true);
        m_Player_Attack_02 = m_Player.FindAction("Attack_02", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Attack_01;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_ChangeUP;
    private readonly InputAction m_Player_ChangeDown;
    private readonly InputAction m_Player_Attack_02;
    private readonly InputAction m_Player_Run;
    public struct PlayerActions
    {
        private @InputAction_1 m_Wrapper;
        public PlayerActions(@InputAction_1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack_01 => m_Wrapper.m_Player_Attack_01;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @ChangeUP => m_Wrapper.m_Player_ChangeUP;
        public InputAction @ChangeDown => m_Wrapper.m_Player_ChangeDown;
        public InputAction @Attack_02 => m_Wrapper.m_Player_Attack_02;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Attack_01.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_01;
                @Attack_01.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_01;
                @Attack_01.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_01;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @ChangeUP.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeUP;
                @ChangeUP.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeUP;
                @ChangeUP.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeUP;
                @ChangeDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeDown;
                @ChangeDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeDown;
                @ChangeDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeDown;
                @Attack_02.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_02;
                @Attack_02.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_02;
                @Attack_02.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack_02;
                @Run.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Attack_01.started += instance.OnAttack_01;
                @Attack_01.performed += instance.OnAttack_01;
                @Attack_01.canceled += instance.OnAttack_01;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @ChangeUP.started += instance.OnChangeUP;
                @ChangeUP.performed += instance.OnChangeUP;
                @ChangeUP.canceled += instance.OnChangeUP;
                @ChangeDown.started += instance.OnChangeDown;
                @ChangeDown.performed += instance.OnChangeDown;
                @ChangeDown.canceled += instance.OnChangeDown;
                @Attack_02.started += instance.OnAttack_02;
                @Attack_02.performed += instance.OnAttack_02;
                @Attack_02.canceled += instance.OnAttack_02;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnAttack_01(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnChangeUP(InputAction.CallbackContext context);
        void OnChangeDown(InputAction.CallbackContext context);
        void OnAttack_02(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
    }
}
